server:
  port: 8082
  servlet:
    context-path: "/gpa-clinica-crm"

spring:
  application:
    name: clinica-crm-api
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=DB_CLINICA;encrypt=false
    username: sa
    password: SuperFood#!
    jpa:
      generate-ddl: false
      hibernate:
        ddl-auto: none
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.SQLServerDialect
          globally_quoted_identifiers: true
    flyway:
      enabled: true
      url: jdbc:sqlserver://localhost:1433;databaseName=DB_CLINICA;encrypt=false
      user: sa
      password: SuperFood#!
      locations: classpath:db/migration

springdoc:
  swagger-ui:
    path: /documentacao
  api-docs:
    path: /api-docs

api:
  security:
    jwt:
      secret-key: D41D8CD98F00B204E9800998ECF8427E
      issuer: clinica-crm-api
