server:
  port: 8082
  servlet:
    context-path: "/gpa-clinica-crm"

spring:
  application:
    name: clinica-crm-api
  jpa:
    open-in-view: false

  datasource:
    url: ${DB_URI}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    jpa:
      generate-ddl: false
      hibernate:
        ddl-auto: none
      show-sql: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.SQLServerDialect
          globally_quoted_identifiers: true
    flyway:
      enabled: true
      url: ${DB_URI}
      user: ${DB_USER}
      password: ${DB_PASSWORD}
      locations: classpath:db/migration

springdoc:
  swagger-ui:
    path: /documentacao
  api-docs:
    path: /api-docs

api:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      issuer: ${JWT_ISSUER}
